### ISSUE TITLE
Сделать Logger

### ISSUE THREAD

**Issue by Kobyylkinss** [LionZXY/BMSTUWiFi#6]
Сделать логгер.

**Comment by LionZXY** [comment]
- [x] Сохранение в файл
- [ ] Механизм отправки лога 
- [x] Доделать механизм логгирования эксепшонов
- [x] По нажатию на нотификацию сделать открытие лога

**Comment by LionZXY** [comment]
Commit 8e68a76. Сделал сохранение в файл, запрос разрешений, доделал метод logAboutCrash. Теперь он еще в добавок и отправляет ошибку на FireBase
